--Used for getting EOM storage lines*/           /*OK as of Nov 2012    */
SELECT  NI_ENTRY, NI_TRAN_TYPE,NI_STATUS,NI_ERA, NI_QUANTITY, NE_AVAIL_ACTUAL, IL_LOCN, IM_STOCK, IM_CUST, IL_NOTE_2 , Sum(NE_AVAIL_ACTUAL) AS "TotalSOH", Count(IL_LOCN) AS "NumOfLocns"
FROM PWIN175.NI, PWIN175.NE, PWIN175.IL, PWIN175.IM , PWIN175.RM
WHERE IL_LOCN = NI_LOCN
AND NI_ENTRY = NE_ENTRY
AND NI_STOCK = IM_STOCK
AND RM_CUST = IM_CUST
/*AND (RM_SOURCE = 'BSPRINTNSW')    */
AND (RM_ANAL = '21VICP')
AND NE_AVAIL_ACTUAL >= '1'
GROUP BY NI_ENTRY, NI_TRAN_TYPE,NI_STATUS,NI_ERA, NI_QUANTITY, NE_AVAIL_ACTUAL, IL_LOCN, IM_STOCK, IM_CUST,IL_NOTE_2
ORDER BY IM_STOCK
--End EOM Storage
