
  --Now get all items with past warehouse items
  SELECT 
  i.IM_STOCK As "Stock",
  SUM(e.NE_AVAIL_ACTUAL) As "Avail",
  SUM(e.NE_QUANTITY) As "Qty",
  TOTAL_SOH_BY_STOCK(i.IM_STOCK) As "SOH"
  FROM  NA n INNER JOIN IL l ON l.IL_UID = n.NA_EXT_KEY
        INNER JOIN NE e ON e.NE_ACCOUNT = n.NA_ACCOUNT
        INNER JOIN IM i ON i.IM_STOCK = n.NA_STOCK
  WHERE (e.NE_TRAN_TYPE = 1 or e.NE_TRAN_TYPE = 6) 
  AND (e.NE_DATE >= '01-AUG-2014' And e.NE_DATE <= '01-AUG-2016')
  AND l.IL_IN_LOCN NOT IN ('OBSOLETEMEL','OBSOLETESYD','PASTHISTORY', 'CANBERRA')
  AND e.NE_STRENGTH = 3
  AND i.IM_ACTIVE = 1
  --AND i.IM_STOCK = 'RTA45070085'
  Group By i.IM_STOCK
  
  UNION ALL
  
  --Now get all items with available stock
  SELECT 
  i.IM_STOCK As "Stock",
  SUM(e.NE_AVAIL_ACTUAL) As "Avail",
  SUM(e.NE_QUANTITY) As "Qty",
  TOTAL_SOH_BY_STOCK(i.IM_STOCK) As "SOH"
  FROM  NA n INNER JOIN IL l ON l.IL_UID = n.NA_EXT_KEY
        INNER JOIN NE e ON e.NE_ACCOUNT = n.NA_ACCOUNT
        INNER JOIN IM i ON i.IM_STOCK = n.NA_STOCK
  WHERE n.NA_EXT_TYPE = 1210067
  AND (e.NE_AVAIL_ACTUAL >= '1') 
  AND l.IL_IN_LOCN NOT IN ('OBSOLETEMEL','OBSOLETESYD','PASTHISTORY', 'CANBERRA')
  AND e.NE_STRENGTH = 3
  AND i.IM_ACTIVE = 1
  --AND i.IM_STOCK = 'RTA45091000K'
  Group By i.IM_STOCK
  
  UNION ALL
  
  --Now get all kitset items with SOH as 99999 and Keep Levels no
  SELECT
  i.IM_STOCK As "Stock",
  NULL As "Avail",
  NULL As "Qty",
  TOTAL_SOH_BY_STOCK(i.IM_STOCK) As "SOH"
  FROM IM i 
  WHERE i.IM_XX_PLUM_STOCK_TYPE = 3
  AND i.IM_ACTIVE = 1
  --AND i.IM_STOCK = 'BL/0360'
  Group By i.IM_STOCK

  UNION ALL
  
  --Now get all download only items
  SELECT
  i.IM_STOCK As "Stock",
  SUM(e.NE_AVAIL_ACTUAL) As "Avail",
  SUM(e.NE_QUANTITY) As "Qty",
  TOTAL_SOH_BY_STOCK(i.IM_STOCK) As "SOH"
  FROM  NA n INNER JOIN IL l ON l.IL_UID = n.NA_EXT_KEY
        INNER JOIN NE e ON e.NE_ACCOUNT = n.NA_ACCOUNT
        INNER JOIN IM i ON i.IM_STOCK = n.NA_STOCK
  WHERE i.IM_KEEP_LEVELs = 0
  AND i.IM_ACTIVE = 1
  AND TOTAL_SOH_BY_STOCK(i.IM_STOCK) > 99999
 -- AND i.IM_STOCK = 'BL/0360'
  Group By i.IM_STOCK;