//'Pickslip Count by Parent '/
SELECT Count(ST_PICK) AS "Number Of Picks", ST_ORDER, RM_CUST
FROM SH, RM ,ST
WHERE SH_CUST = RM_CUST
AND RM_PARENT LIKE '21%'
AND ST_ORDER = SH_ORDER
GROUP BY ST_ORDER,RM_CUST


//'Pickslip Count by Cust '/
SELECT Count(ST_PICK) AS "Number Of Picks", ST_ORDER, RM_CUST
FROM SH, RM ,ST
WHERE SH_CUST = RM_CUST
AND RM_PARENT = '' AND RM_CUST LIKE '21*'
AND ST_ORDER = SH_ORDER
GROUP BY ST_ORDER,RM_CUST



//'Order Count by Parent  '/
SELECT Count(SH_ORDER) AS "Number Of Orders", SH_ORDER, RM_CUST
FROM SH, RM
WHERE SH_CUST = RM_CUST
AND RM_PARENT LIKE '21%'
GROUP BY SH_ORDER,RM_CUST


//'Order Count by Cust  '/
SELECT Count(SH_ORDER) AS "Number Of Orders", SH_ORDER, RM_CUST
FROM SH, RM
WHERE SH_CUST = RM_CUST
AND RM_PARENT = '' AND RM_CUST LIKE '21*'
GROUP BY SH_ORDER,RM_CUST




//'SD Count by Parent  '/
SELECT SD_ORDER, RM_CUST, RM_PARENT,
CASE
  WHEN SH_STATUS = 0 THEN 'AWAITING '
  WHEN SH_STATUS = 1 THEN 'LIVE '
  WHEN SH_STATUS = 2 THEN 'DESPATCHED '
  WHEN SH_STATUS = 3 THEN 'CANCELLED '
  WHEN SH_STATUS = 4 THEN 'CLOSED '
END AS SH_STATUS,
CASE
  WHEN SD_STATUS = 0 THEN 'AWAITING '
  WHEN SD_STATUS = 1 THEN 'LIVE '
  WHEN SD_STATUS = 2 THEN 'DESPATCHED '
  WHEN SD_STATUS = 3 THEN 'CANCELLED '
  WHEN SD_STATUS = 4 THEN 'CLOSED '
END AS SD_STATUS,   SD_LINE
FROM SH, RM ,SD
WHERE SH_CUST = RM_CUST
AND SD_ORDER = SH_ORDER
AND RM_PARENT LIKE '21%'
GROUP BY SD_ORDER, RM_CUST, RM_PARENT, SH_STATUS, SD_STATUS, SD_LINE
ORDER BY SD_ORDER, SD_LINE



//'SD Count by Cust  '/
SELECT SD_ORDER, SH_CUST, RM_PARENT,
CASE
  WHEN SH_STATUS = 0 THEN 'AWAITING '
  WHEN SH_STATUS = 1 THEN 'LIVE '
  WHEN SH_STATUS = 2 THEN 'DESPATCHED '
  WHEN SH_STATUS = 3 THEN 'CANCELLED '
  WHEN SH_STATUS = 4 THEN 'CLOSED '
END AS SH_STATUS,
CASE
  WHEN SD_STATUS = 0 THEN 'AWAITING '
  WHEN SD_STATUS = 1 THEN 'LIVE '
  WHEN SD_STATUS = 2 THEN 'DESPATCHED '
  WHEN SD_STATUS = 3 THEN 'CANCELLED '
  WHEN SD_STATUS = 4 THEN 'CLOSED '
END AS SD_STATUS,   SD_LINE
FROM SH, RM ,SD
WHERE SH_CUST = RM_CUST
AND SD_ORDER  = SH_ORDER
AND RM_CUST   IN ( '21ACROW','21ELILILLY', '21IOOF', '21JELDWEN', '21QBEINSUR')
GROUP BY SD_ORDER, SH_CUST, RM_PARENT, SH_STATUS, SD_STATUS , SD_LINE
ORDER BY SD_ORDER, SD_LINE

select
   object_name, 
   object_type, 
   last_ddl_time
from
   dba_objects
where object_type = 'TABLE'
and
  object_name Like '%Dev%';

SELECT LAST_DDL_TIME, TIMESTAMP
FROM USER_OBJECTS
WHERE OBJECT_TYPE = 'PROCEDURE'
AND OBJECT_NAME = 'MY_PROC';  