--------------------------------------------------------
--  File created - Friday-November-13-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEV_ADMIN
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ADMIN" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_ADMIN_DATA_BREAKPRICES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ADMIN_DATA_BREAKPRICES" 
   (	"VIISTOCK" VARCHAR2(30 BYTE), 
	"VIICUST" VARCHAR2(20 BYTE), 
	"VUNITPRICE" NUMBER, 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_ADMIN_DATA_CUST
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ADMIN_DATA_CUST" 
   (	"VCUST" VARCHAR2(200 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_ADMIN_DATA_PICK_LINECOUNTS
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ADMIN_DATA_PICK_LINECOUNTS" 
   (	"NCOUNTOFLINES" NUMBER, 
	"VSLPICKSLIPNUM" VARCHAR2(10 BYTE), 
	"VSLORDERNUM" VARCHAR2(10 BYTE), 
	"VSLPSLIP" VARCHAR2(10 BYTE), 
	"VDATEDESPSL" VARCHAR2(255 BYTE), 
	"VPACKAGESSL" NUMBER, 
	"VWEIGHTSL" NUMBER, 
	"VST_XX_NUM_PAL_SW_SL" NUMBER, 
	"VST_XX_NUM_PALLETS_SL" NUMBER, 
	"VST_XX_NUM_CARTONS_SL" NUMBER, 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_ADMIN_DATA_PICKSLIPS
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ADMIN_DATA_PICKSLIPS" 
   (	"VPICKSLIP" VARCHAR2(200 BYTE), 
	"VPSLIP" VARCHAR2(10 BYTE), 
	"VDATEDESP" DATE, 
	"VPACKAGES" NUMBER, 
	"VWEIGHT" NUMBER, 
	"VST_XX_NUM_PAL_SW" NUMBER, 
	"VST_XX_NUM_PALLETS" NUMBER, 
	"VST_XX_NUM_CARTONS" NUMBER, 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_ADMIN_DATA2
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ADMIN_DATA2" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"NIAVAILACTUAL" NUMBER, 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_ALL_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ALL_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"DESPNOTE" VARCHAR2(255 BYTE), 
	"DESPDATE" VARCHAR2(255 BYTE), 
	"ORDERDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_ALL_FEES_F
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ALL_FEES_F" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"DESPNOTE" VARCHAR2(255 BYTE), 
	"DESPDATE" VARCHAR2(255 BYTE), 
	"ORDERDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_ALL_FREIGHT
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ALL_FREIGHT" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"DESPNOTE" VARCHAR2(255 BYTE), 
	"DESPDATE" VARCHAR2(255 BYTE), 
	"ORDERDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICEMARKEDUP" NUMBER, 
	"SDSELL" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"SDXXFREIGHTCHG" NUMBER, 
	"SDNOTE1" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_ALL_FREIGHT_ALL
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ALL_FREIGHT_ALL" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"DESPNOTE" VARCHAR2(255 BYTE), 
	"DESPDATE" VARCHAR2(255 BYTE), 
	"ORDERDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICEMARKEDUP" NUMBER, 
	"SDSELL" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"SDXXFREIGHTCHG" NUMBER, 
	"SDNOTE1" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_ALL_FREIGHT_F
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ALL_FREIGHT_F" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"DESPNOTE" VARCHAR2(255 BYTE), 
	"DESPDATE" VARCHAR2(255 BYTE), 
	"ORDERDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICEMARKEDUP" NUMBER, 
	"SDSELL" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"SDXXFREIGHTCHG" NUMBER, 
	"SDNOTE1" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_ALL_ORD_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ALL_ORD_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"DESPNOTE" VARCHAR2(255 BYTE), 
	"DESPDATE" VARCHAR2(255 BYTE), 
	"ORDERDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_BATCH_PRICE_SL_STOCK
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_BATCH_PRICE_SL_STOCK" 
   (	"VBATCHSTOCK" VARCHAR2(30 BYTE), 
	"VBATCHPICKNUM" VARCHAR2(10 BYTE), 
	"VDEXCL" NUMBER, 
	"VUNITPRICE" NUMBER, 
	"VQUANTITY" NUMBER, 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_CTN_DESP_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_CTN_DESP_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_CTN_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_CTN_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_CTN_IN_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_CTN_IN_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_CUST_REPORTING
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_CUST_REPORTING" 
   (	"SCUST" VARCHAR2(20 BYTE), 
	"SHEADERS" VARCHAR2(1000 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_CUSTOMER_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_CUSTOMER_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_DESP_REPT
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_DESP_REPT" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"NIAVAILACTUAL" NUMBER, 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"ORDERDATE" VARCHAR2(255 BYTE), 
	"PICKPRINTEDDATE" VARCHAR2(255 BYTE), 
	"PICKOP" VARCHAR2(255 BYTE), 
	"PICKDATE" VARCHAR2(255 BYTE), 
	"POSTDATE" VARCHAR2(255 BYTE), 
	"POSTWEIGHT" VARCHAR2(12 BYTE), 
	"BOFLAG" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_DESP_REPT2
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_DESP_REPT2" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"NIAVAILACTUAL" NUMBER, 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"ORDERDATE" VARCHAR2(255 BYTE), 
	"PICKPRINTEDDATE" VARCHAR2(255 BYTE), 
	"PICKOP" VARCHAR2(255 BYTE), 
	"PICKDATE" VARCHAR2(255 BYTE), 
	"POSTDATE" VARCHAR2(255 BYTE), 
	"POSTWEIGHT" VARCHAR2(12 BYTE), 
	"BOFLAG" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_DESTROY_ORD_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_DESTROY_ORD_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_DROP_LIST
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_DROP_LIST" 
   (	"DV_INDEX" NUMBER, 
	"DV_VALUE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_EMAIL_ORD_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_EMAIL_ORD_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_EOM_LOGS
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_EOM_LOGS" 
   (	"DATETIME" DATE, 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"ORIGIN_PROCESS" VARCHAR2(250 BYTE), 
	"ORIGIN_TBL" VARCHAR2(250 BYTE), 
	"DEST_TBL" VARCHAR2(250 BYTE), 
	"TIME_TAKEN" VARCHAR2(50 BYTE), 
	"CUST" VARCHAR2(50 BYTE), 
	"LAST_SUC_FIN" TIMESTAMP (8)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_FAX_ORD_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_FAX_ORD_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_FREIGHT
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_FREIGHT" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"AddDate" VARCHAR2(255 BYTE), 
	"AddOp" VARCHAR2(255 BYTE), 
	"IFSSELL" VARCHAR2(255 BYTE), 
	"IFSCOST" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_GROUP_CUST
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_GROUP_CUST" 
   (	"SGROUPCUST" VARCHAR2(20 BYTE), 
	"SCUST" VARCHAR2(20 BYTE), 
	"NLEVEL" NUMBER, 
	"AREA" VARCHAR2(255 BYTE), 
	"TERR" VARCHAR2(255 BYTE), 
	"RMDBL2" VARCHAR2(255 BYTE), 
	"ANAL" VARCHAR2(255 BYTE), 
	"SOURCE" VARCHAR2(255 BYTE), 
	"OW_CAT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_GROUP_CUST2
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "PWIN175"."DEV_GROUP_CUST2" 
   (	"SGRPCUST" VARCHAR2(30 BYTE), 
	"SNAME" VARCHAR2(120 BYTE), 
	"SCUST" VARCHAR2(30 BYTE), 
	"SPARENT" VARCHAR2(30 BYTE), 
	"NLEVEL" NUMBER, 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) ON COMMIT DELETE ROWS ;
--------------------------------------------------------
--  DDL for Table DEV_HAND_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_HAND_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_HANDLING_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_HANDLING_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"DESPNOTE" VARCHAR2(255 BYTE), 
	"DESPDATE" VARCHAR2(255 BYTE), 
	"ORDERDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_IM_LOG_DATA
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_IM_LOG_DATA" 
   (	"TABLE_COLUMN_NAME" VARCHAR2(50 BYTE), 
	"STOCK_CODE" VARCHAR2(21 BYTE), 
	"MOD_OP" VARCHAR2(7 BYTE), 
	"MOD_NAME" VARCHAR2(35 BYTE), 
	"MOD_DATE" DATE DEFAULT TO_DATE('0001-01-01','YYYY-MM-DD'), 
	"MOD_TIME" NUMBER DEFAULT NULL, 
	"NEW_VALUE" VARCHAR2(50 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IT_TEMP" ;
--------------------------------------------------------
--  DDL for Table DEV_LOCN_CNT_BY_CUST
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_LOCN_CNT_BY_CUST" 
   (	"NCOUNTOFSTOCKS" NUMBER, 
	"SLOCN" VARCHAR2(20 BYTE), 
	"SCUST" VARCHAR2(20 BYTE), 
	"SNOTE" VARCHAR2(20 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_LOG_CNTS
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_LOG_CNTS" 
   (	"Warehouse" VARCHAR2(20 BYTE), 
	"Customer" VARCHAR2(20 BYTE), 
	"Type" VARCHAR2(20 BYTE), 
	"TotalCount" VARCHAR2(20 BYTE), 
	"Charge" VARCHAR2(20 BYTE), 
	"TotalValue" VARCHAR2(20 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_LOG_STATS
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_LOG_STATS" 
   (	"SWAREHOUSE" VARCHAR2(50 BYTE), 
	"SCUST" VARCHAR2(50 BYTE), 
	"NTOTAL" NUMBER, 
	"STYPE" VARCHAR2(50 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_M_FREIGHT
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_M_FREIGHT" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"AddDate" VARCHAR2(255 BYTE), 
	"AddOp" VARCHAR2(255 BYTE), 
	"IFSSELL" VARCHAR2(255 BYTE), 
	"IFSCOST" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_M_XX_FREIGHT
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_M_XX_FREIGHT" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"AddDate" VARCHAR2(255 BYTE), 
	"AddOp" VARCHAR2(255 BYTE), 
	"IFSSELL" VARCHAR2(255 BYTE), 
	"IFSCOST" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_MAN_ORD_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_MAN_ORD_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_MISC_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_MISC_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_ORD_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_ORD_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_PACKING_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_PACKING_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_PAL_CTN_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_PAL_CTN_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_PAL_DESP_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_PAL_DESP_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_PAL_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_PAL_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_PAL_IN_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_PAL_IN_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_PHONE_ORD_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_PHONE_ORD_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_PICK_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_PICK_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"DESPNOTE" VARCHAR2(255 BYTE), 
	"DESPDATE" VARCHAR2(255 BYTE), 
	"ORDERDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_SD_FR_DATA
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_SD_FR_DATA" 
   (	"TABLE_COLUMN_NAME" VARCHAR2(50 BYTE), 
	"STOCK_CODE" VARCHAR2(21 BYTE), 
	"MOD_OP" VARCHAR2(7 BYTE), 
	"MOD_NAME" VARCHAR2(35 BYTE), 
	"MOD_DATE" DATE, 
	"MOD_TIME" NUMBER, 
	"NEW_VALUE" VARCHAR2(50 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_SEC_STOR_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_SEC_STOR_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_SHRINKWRAP_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_SHRINKWRAP_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_SLOW_STOR_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_SLOW_STOR_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_STD_ORD_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_STD_ORD_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_STOCK_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_STOCK_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_STOR_ALL_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_STOR_ALL_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_STOR_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_STOR_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_TBL_COUNTS
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_TBL_COUNTS" 
   (	"TABLE_NAME" VARCHAR2(40 BYTE), 
	"COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_V_FREIGHT
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_V_FREIGHT" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPNOTE" VARCHAR2(255 BYTE), 
	"ORDERDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OWUNITPRICE" NUMBER, 
	"SELLEXCL" NUMBER, 
	"SELLINCL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"PREMARKUPSELL" NUMBER, 
	"COSTPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"ADDDATE" VARCHAR2(255 BYTE), 
	"ADDOP" VARCHAR2(255 BYTE), 
	"XXFREIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Table DEV_VERBAL_ORD_FEES
--------------------------------------------------------

  CREATE TABLE "PWIN175"."DEV_VERBAL_ORD_FEES" 
   (	"CUSTOMER" VARCHAR2(255 BYTE), 
	"PARENT" VARCHAR2(255 BYTE), 
	"COSTCENTRE" VARCHAR2(255 BYTE), 
	"ORDERNUM" VARCHAR2(255 BYTE), 
	"ORDERWARENUM" VARCHAR2(255 BYTE), 
	"CUSTREF" VARCHAR2(255 BYTE), 
	"PICKSLIP" VARCHAR2(255 BYTE), 
	"PICKNUM" VARCHAR2(255 BYTE), 
	"DESPATCHNOTE" VARCHAR2(255 BYTE), 
	"DESPATCHDATE" VARCHAR2(255 BYTE), 
	"FEETYPE" VARCHAR2(255 BYTE), 
	"ITEM" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"QTY" NUMBER, 
	"UOI" VARCHAR2(255 BYTE), 
	"UNITPRICE" NUMBER, 
	"OW_UNIT_SELL_PRICE" NUMBER, 
	"SELL_EXCL" NUMBER, 
	"SELL_EXCL_TOTAL" NUMBER, 
	"SELL_INCL" NUMBER, 
	"SELL_INCL_TOTAL" NUMBER, 
	"REPORTINGPRICE" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS2" VARCHAR2(255 BYTE), 
	"SUBURB" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"POSTCODE" VARCHAR2(255 BYTE), 
	"DELIVERTO" VARCHAR2(255 BYTE), 
	"ATTENTIONTO" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"PACKAGES" NUMBER, 
	"ORDERSOURCE" NUMBER(*,0), 
	"ILNOTE2" VARCHAR2(255 BYTE), 
	"NILOCN" VARCHAR2(255 BYTE), 
	"COUNTOFSTOCKS" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"BRAND" VARCHAR2(255 BYTE), 
	"OWNEDBY" VARCHAR2(255 BYTE), 
	"SPROFILE" VARCHAR2(255 BYTE), 
	"WAIVEFEE" VARCHAR2(255 BYTE), 
	"COST" VARCHAR2(255 BYTE), 
	"PAYMENTTYPE" VARCHAR2(255 BYTE), 
	"CAMPAIGN" VARCHAR2(255 BYTE), 
	"SPARE1" VARCHAR2(255 BYTE), 
	"SPARE2" VARCHAR2(255 BYTE), 
	"SPARE3" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  DDL for Index LAST_TOUCHED
--------------------------------------------------------

  CREATE INDEX "PWIN175"."DEV_LAST_TOUCHED" ON "PWIN175"."DEV_EOM_LOGS" ("DATETIME" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PWIN5" ;
--------------------------------------------------------
--  Constraints for Table DEV_DROP_LIST
--------------------------------------------------------

  ALTER TABLE "PWIN175"."DEV_DROP_LIST" MODIFY ("DV_INDEX" NOT NULL ENABLE);
 
  ALTER TABLE "PWIN175"."DEV_DROP_LIST" MODIFY ("DV_VALUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEV_EOM_LOGS
--------------------------------------------------------

  ALTER TABLE "PWIN175"."DEV_EOM_LOGS" MODIFY ("DATETIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEV_IM_LOG_DATA
--------------------------------------------------------

  ALTER TABLE "PWIN175"."DEV_IM_LOG_DATA" MODIFY ("TABLE_COLUMN_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "PWIN175"."DEV_IM_LOG_DATA" MODIFY ("STOCK_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PWIN175"."DEV_IM_LOG_DATA" MODIFY ("MOD_OP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEV_SD_FR_DATA
--------------------------------------------------------

  ALTER TABLE "PWIN175"."DEV_SD_FR_DATA" MODIFY ("TABLE_COLUMN_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "PWIN175"."DEV_SD_FR_DATA" MODIFY ("STOCK_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PWIN175"."DEV_SD_FR_DATA" MODIFY ("MOD_OP" NOT NULL ENABLE);
