
                                                YH_CODE_ID in ( select RH_YH_CODE_ID from PWIN175.RH TBLRH  where RH_ACTIVE=1 and RH_USE_IN_QJ!=0 and RH_RM_UID=102389 )





  SELECT RM_CUST, RM_EDIT_OP, RM_EDIT_DATE,RM_ANAL, YH_NAME FROM RM LEFT JOIN RH ON RH_RM_UID = RM_UID INNER JOIN YH ON YH_CODE_ID = RH_YH_CODE_ID WHERE RM_EDIT_DATE >= '1-Sep-2014'



  SELECT QM_UID,QM_CUST_CODE, QM_JOB_NUM,QM_QUOTE_NUM,RJ_EXT_KEY, QM_ADD_DATE, QM_ADD_OP, RM_UID, RI_CODE,RI_DEFAULT_NOTE
  FROM QM
  INNER JOIN RJ ON RJ_EXT_KEY = QM_UID
  INNER JOIN RI ON RI_AVAIL_CODE_ID = RJ_RI_AVAIL_CODE_ID
  INNER JOIN RM ON RM_CUST = QM_CUST_CODE
  WHERE QM_CUST_CODE IN (   SELECT RM_CUST
  FROM RM LEFT INNER JOIN RH ON RH_RM_UID = RM_UID
  INNER JOIN RI ON RI_RH_REF_CODE_ID = RH_REF_CODE_ID
  --INNER JOIN RJ ON RJ_RI_AVAIL_CODE_ID = RI_AVAIL_CODE_ID
  INNER JOIN YH ON YH_CODE_ID = RH_YH_CODE_ID
  WHERE RM_PARENT LIKE 'AMP%'  AND RI_DEFAULT_IN_QJ = 1 )
  --AND QM_CUST_CODE = 'FX080'
  AND QM_ADD_DATE >= '25-Aug-2014'
  --AND QM_JOB_STATUS IN (5,6,7,8,9,10)
  AND  QM_QUOTE_STATUS IN (5,6,7,8,9,10)
  --AND RI_CODE NOT LIKE 'FD%'
   ORDER BY 1,2





  SELECT RM_CUST
  FROM RM LEFT INNER JOIN RH ON RH_RM_UID = RM_UID
  INNER JOIN RI ON RI_RH_REF_CODE_ID = RH_REF_CODE_ID
  --INNER JOIN RJ ON RJ_RI_AVAIL_CODE_ID = RI_AVAIL_CODE_ID
  INNER JOIN YH ON YH_CODE_ID = RH_YH_CODE_ID
  WHERE RM_PARENT LIKE 'AMP%'  AND RI_DEFAULT_IN_QJ = 1


  SELECT RJ_EXT_KEY
  FROM QM
  INNER JOIN RJ ON RJ_EXT_KEY = QM_UID
  INNER JOIN RI ON RI_AVAIL_CODE_ID = RJ_RI_AVAIL_CODE_ID
  INNER JOIN RM ON RM_CUST = QM_CUST_CODE
  WHERE QM_CUST_CODE Like 'FX%'  --QM_CUST_CODE Like 'AMP%' OR
  AND QM_JOB_STATUS IN (5,6,7,8,9,10)
  ORDER BY 1



  SELECT * FROM RJ WHERE RJ_EXT_KEY = 835214 --IN (295440)

  DELETE FROM RJ WHERE RJ_EXT_KEY
  IN (
  SELECT QM_UID
  FROM QM
  INNER JOIN RJ ON RJ_EXT_KEY = QM_UID
  INNER JOIN RI ON RI_AVAIL_CODE_ID = RJ_RI_AVAIL_CODE_ID
  INNER JOIN RM ON RM_CUST = QM_CUST_CODE
  WHERE QM_CUST_CODE IN (   SELECT RM_CUST
  FROM RM LEFT INNER JOIN RH ON RH_RM_UID = RM_UID
  INNER JOIN RI ON RI_RH_REF_CODE_ID = RH_REF_CODE_ID
  --INNER JOIN RJ ON RJ_RI_AVAIL_CODE_ID = RI_AVAIL_CODE_ID
  INNER JOIN YH ON YH_CODE_ID = RH_YH_CODE_ID
  WHERE RM_PARENT LIKE 'AMP%'  AND RI_DEFAULT_IN_QJ = 1 )
  --AND QM_CUST_CODE = 'FX080'
  AND QM_ADD_DATE >= '25-Aug-2014'
  AND QM_QUOTE_STATUS IN (5,6,7,8,9,10)
  )