SELECT IM_STOCK, IM_BRAND, IM_XX_COST_CENTRE01, IM_CUST, IM_ACTIVE
FROM IM
WHERE IM_CUST = 'AAS' AND IM_ACTIVE = 1  AND IM_BRAND = 'AAS_TWU'


SELECT IR_BRAND, IR_DESC FROM IR WHERE SubStr(IR_BRAND,0,4) = 'AAS_'

SELECT RM_CUST, RM_NAME FROM RM WHERE SubStr(RM_CUST,0,4) = 'AAS_'
