SELECT Count(SL_PICK)
FROM  SL
WHERE SL_ORDER = '   1795348' AND SL_PICK = '   3064835'  ORDER BY SL_PICK,SL_LINE ASC;         --12

SELECT SL_ORDER_LINE,SD_LINE, SD_STOCK, SL_ORDER --,SL_LINE, SD_LINE, SL_ORDER_LINE--,Count(SL_PICK)
FROM  SL
INNER JOIN SD ON SD_LINE  = SL_ORDER_LINE AND SD_LAST_PICK_NUM = SL_PICK
INNER JOIN SH ON SH_ORDER  = SD_ORDER
INNER JOIN Tmp_Group_Cust ON sCust = SH_CUST
INNER JOIN IM ON IM_STOCK = SD_STOCK
--INNER JOIN NI ON NI_NV_EXT_KEY = SL_UID
INNER JOIN IU ON IU_UNIT = IM_LEVEL_UNIT

WHERE SL_ORDER = '   1795348' AND SL_PICK = '   3064835'


SELECT Count(SL_PICK)
FROM  PWIN175.SD d
RIGHT JOIN PWIN175.SH s  ON s.SH_ORDER  = d.SD_ORDER
LEFT JOIN PWIN175.ST t  ON t.ST_PICK  = d.SD_LAST_PICK_NUM
RIGHT OUTER JOIN PWIN175.SL l   ON l.SL_PICK   = t.ST_PICK
LEFT JOIN Tmp_Group_Cust r ON r.sCust = s.SH_CUST
INNER JOIN PWIN175.IM i  ON i.IM_STOCK = d.SD_STOCK
INNER JOIN PWIN175.NI n  ON n.NI_NV_EXT_KEY = l.SL_UID
INNER JOIN IU ON IU_UNIT = IM_LEVEL_UNIT
WHERE SL_ORDER = '   1795348' AND SL_PICK = '   3064835'  ORDER BY SL_PICK,SL_LINE ASC;


SELECT * FROM TMP_PICK_FEES


SELECT l.SL_LINE,l.SL_ORDER,t.ST_PICK

--SELECT Count(s.SH_ORDER)
FROM  SD d
INNER JOIN SH s  ON s.SH_ORDER  = d.SD_ORDER
--INNER JOIN ST t  ON t.ST_PICK  = d.SD_LAST_PICK_NUM
INNER JOIN SL l  ON l.SL_ORDER  = d.SD_ORDER  AND SL_ORDER_LINE = SD_LINE
INNER JOIN ST t  ON t.ST_PICK  = l.SL_PICK
INNER JOIN Tmp_Group_Cust r ON r.sCust = s.SH_CUST
INNER JOIN IM i  ON i.IM_STOCK = d.SD_STOCK
--INNER JOIN NE n  ON n.NE_STOCK = l.SL_UID
INNER JOIN IU ON IU_UNIT = i.IM_LEVEL_UNIT
WHERE SD_STATUS != 3
AND SL_PSLIP_QTY >= 1
AND (r.sGroupCust = 'TABCORP' OR r.sCust = 'TABCORP')
--AND       s.SH_ORDER = t.ST_ORDER
--AND       TO_CHAR(t.ST_DESP_DATE,'YYYY-MM-DD') >= start_date AND TO_CHAR(t.ST_DESP_DATE,'YYYY-MM-DD') <= end_date
AND       t.ST_DESP_DATE >= '05-Oct-2015' AND t.ST_DESP_DATE <= '11-Oct-2015'
AND
SL_ORDER = '   1796545' AND SL_PICK = '   3066174'  ;
/

SELECT * FROM Tmp_Admin_Data_Pick_LineCounts  WHERE vslpickslipnum = '   3066174'


Select * From TMP_ALL_FEES_F