USE [LiveData]
GO
SELECT	sku.[INVENTORY CODE],
		STKLOCLN.LOCATION AS Locn, 
		d.[AC NO] As Cust, 
		CAST([dbo].[ufnGetStockSOH] (sku.[INVENTORY CODE]) AS INT) As SOH
FROM STKLOCLN
	INNER JOIN PAPSIZE sku ON sku.[INVENTORY CODE] = STKLOCLN.[PAPSIZE RECNUM]
	LEFT JOIN DEBTOR d ON d.[DATAFLEX RECNUM ONE] = sku.[DEBTOR RECNUM]

WHERE sku.ACTIVE = 1
	AND sku.[INVENTORY CODE] = 'RCV609973_A'
		
GROUP BY STKLOCLN.LOCATION,d.[AC NO],CAST( sku.[INVENTORY CODE] as varchar),sku.[INVENTORY CODE]

SELECT CAST([dbo].[ufnGetStockSOH] ('RCV609973_A') AS INT)
GO



--THIS WORKS BELOW
USE [LiveData]
GO

SELECT sku.[INVENTORY CODE],CAST([dbo].[ufnGetStockSOH] (sku.[INVENTORY CODE]) AS INT) As SOH
FROM PAPSIZE sku
WHERE CAST([dbo].[ufnGetStockSOH] (sku.[INVENTORY CODE]) AS INT) > 0
GO
