
--THIS WORKS BELOW
USE [LiveData]
GO

SELECT sku.[INVENTORY CODE],CAST([dbo].[ufnGetStockSOH] (sku.[INVENTORY CODE]) AS INT) As SOH
FROM PAPSIZE sku
WHERE sku.ACTIVE = 'Y'
	AND CAST([dbo].[ufnGetStockSOH] (sku.[INVENTORY CODE]) AS INT) > 0
GO
