SELECT RM_CUST
      ,(
        CASE
          WHEN LEVEL = 1 THEN RM_CUST
          WHEN LEVEL = 2 THEN RM_PARENT
          WHEN LEVEL = 3 THEN PRIOR RM_PARENT
          ELSE NULL
        END
      ) AS CC
      ,LEVEL,RM_AREA,RM_TERR,(Select MAX(DV_VALUE) FROM TMP_DROP_LIST Where DV_INDEX = TO_NUMBER(RM_DBL_2)),RM_ANAL,RM_SOURCE,RM_GROUP_CUST
FROM RM
WHERE RM_TYPE = 0
AND RM_ACTIVE = 1
--AND Length(RM_GROUP_CUST) <=  1
CONNECT BY PRIOR RM_CUST = RM_PARENT
START WITH Length(RM_PARENT) <= 1;

Select * From DEV_GROUP_CUST
Where sCUST like 'G-%'
AND AREA = 'FROST';

Declare
  start_date VARCHAR2(20) := '01-Sep-2016';
  end_date VARCHAR2(20) := '30-Sep-2016';
Begin
  SELECT LTrim(ST_PICK),LTrim(ST_PSLIP), substr(To_Char(ST_DESP_DATE),0,10), ST_WEIGHT, ST_PACKAGES,ST_XX_NUM_PAL_SW,ST_XX_NUM_PALLETS,ST_XX_NUM_CARTONS,NULL,NULL,NULL,NULL
  FROM ST LEFT JOIN SH ON SH_ORDER = ST_ORDER
  WHERE ST_DESP_DATE >= '01-Sep-2016' AND ST_DESP_DATE <= '30-Sep-2016'
  AND ST_PSLIP != 'CANCELLED'
  AND SH_STATUS <> 3;
End;